### ISSUE TITLE
No module named 'pygame'

### ISSUE THREAD

**Issue by TWSalm0n** [quasar098/limbos32#11]
When I open start.py :
`Traceback (most recent call last):
  File "C:\Users\User\Downloads\limbos32-master\limbos32-master\main.py", line 2, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'`

**Comment by HHonzik** [comment]
open cmd.exe and run `pip install pygame`, then it will work

**Comment by EMREOYUN** [comment]
`pip install -r requirements.txt` works now
