### ISSUE TITLE
Problem with spawn-all.py

### ISSUE THREAD

**Issue by TotallyNotANormalPerson** [quasar098/limbos32#13]
When i try to run spawn-all.py its saying `python3: can't open file 'C:\\Windows\\System32\\main.py': [Errno 2] No such file or directory`
(btw i have python 3.11)
![image](https://github.com/quasar098/limbos32/assets/150983382/dfdc509d-c20d-4c2f-9057-be93f91d90e5)

**Comment by EMREOYUN** [comment]
Explained in #9

**Comment by quasar098** [comment]
yes
