### ISSUE TITLE
Having problems with spawn-all.py

### ISSUE THREAD

**Issue by Leositor** [quasar098/limbos32#15]
![image](https://github.com/quasar098/limbos32/assets/151980591/926a01d6-c690-473d-bb10-f456960d26d7)

I think I tried two solutions and none of them worked. I can't seem to get it working at all.

**Comment by Ovideul** [comment]
can you give me the file?

**Comment by eversiege** [comment]
Run with just `python`. In `spawn-all.py` change to `python` instead of `python3`.
