### ISSUE TITLE
limbo32 does not work

### ISSUE THREAD

**Issue by githubuser1038** [quasar098/limbos32#16]
i did everything in the description and here is the result
https://drive.google.com/file/d/1_f8B5FfdE8UYrXVFxcCgUMqORe9Spzsy/view?usp=sharing

**Comment by HHonzik** [comment]
python.org python and open cmd, navigate to it and after your in the folder where its located, run `start "" "cmd"` and in the new one write `python server.py` and in the other one `python spawn-all.py`

**Comment by githubuser1038** [comment]
https://drive.google.com/file/d/1-AY92UM_eBsmmJvpokAqewdN9O31eSUd/view?usp=sharing

**Comment by githubuser1038** [comment]
it doesn't work

**Comment by githubuser1038** [comment]
what command?
(also idc if i leak my name, i just want help)

**Comment by githubuser1038** [comment]
![Screenshot (19)](https://github.com/quasar098/limbos32/assets/152592362/4200830b-7461-4f82-a9fb-f9266b0a934a)
btw i clicked on setup.py

**Comment by githubuser1038** [comment]
also here's proof that python works
![Screenshot (20)](https://github.com/quasar098/limbos32/assets/152592362/972d01b1-063d-48f2-996e-16ccb8e3dbe7)

**Comment by githubuser1038** [comment]
no module named pygame

python -m pip install -r requirements.txt
  File "<stdin>", line 1
    python -m pip install -r requirements.txt
                      ^^
 SyntaxError: invalid syntax

**Comment by githubuser1038** [comment]
those arrows where meant to be at the word pip

**Comment by Ovideul** [comment]
yeah same problem

**Comment by Ovideul** [comment]
It says "no <module> named pygame in main.py" and there is a fucking module named pygame

**Comment by quasar098** [comment]
> no module named pygame
> 
> python -m pip install -r requirements.txt File "", line 1 python -m pip install -r requirements.txt ^^ SyntaxError: invalid syntax

stop running it in the python shell. run it in command prompt instead

**Comment by quasar098** [comment]
> It says "no named pygame in main.py" and there is a fucking module named pygame

try listing your modules with pip and check if pygame is there. also use python -m pip instead of just pip when installing modules because having multiple python versions can cause issues with pip

**Comment by Ovideul** [comment]
I tried

lun., 4 dec. 2023, 16:54 quasar098 ***@***.***> a scris:

**Comment by quasar098** [comment]
you need to try harder

**Comment by Ovideul** [comment]
Can you make a video...?

lun., 4 dec. 2023, 21:17 quasar098 ***@***.***> a scris:

**Comment by HHonzik** [comment]
RUN `pip install pygame` and your done
