### ISSUE TITLE
Win error 10061

### ISSUE THREAD

**Issue by FewsStuffHere** [quasar098/limbos32#20]
Whenever i try to run Python spawn-all.py or Python3 spawn-all.py, i got an respond with "[WinError 10061] No connection could be made because the target machine actively refused it."
After that, 8 failed windows titled "LIMBO" would appear but does not work and will not stay on screen
I do not know what leads to this issue, any ideas on how to resolve this?
![image](https://github.com/quasar098/limbos32/assets/153519808/71d67811-d1a9-494e-9239-f63ea4c3c0b9)
![image](https://github.com/quasar098/limbos32/assets/153519808/658c63b3-6a4f-4c3d-8dca-e7d3b68077ec)

**Comment by lucasdaweb95** [comment]
> nvm i fixed it 😭 😭

how tho }:I
