### ISSUE TITLE
just "Python" many times when i do python "spawn-all.py"

### ISSUE THREAD

**Issue by TheZGuy** [quasar098/limbos32#22]
![image](https://github.com/quasar098/limbos32/assets/154070971/fbdea871-4a93-4349-afb4-4f417df876f5)
it just says python every time

**Comment by TheZGuy** [comment]
i fixed it, for anyone who has the same problem go into your code editor and chance system(python3 main.py) to system(python main.py)

**Comment by HHonzik** [comment]
so you can press close&
A)It was in the FAQ
B)Made a (almost) automatic way to fix that without any manual stuff (as a pull request)
