### ISSUE TITLE
Not working scripts

### ISSUE THREAD

**Issue by MrSteveOff** [quasar098/limbos32#24]
So, like how to reproduce this:
Do everything in README, and start the code, and it's not working.

I just do everything run spawn-all.py, and it comes, tons of LIMBO windows with nothing.

**Comment by TheZGuy** [comment]
open server.py in the background

**Comment by HHonzik** [comment]
yes

**Comment by quasar098** [comment]
yes

**Comment by quasar098** [comment]
and ? what happened

**Comment by quasar098** [comment]
closing to inactivity

**Comment by MrSteveOff** [comment]
> and ? what happened

Sorry for not responding, the limbo keys just started to opening without image or code

**Comment by MrSteveOff** [comment]
and without music
