### ISSUE TITLE
"Limbo" Invisible windows and don't know what I have to do.

### ISSUE THREAD

**Issue by MartinLlamas1** [quasar098/limbos32#25]
![Screenshot](https://github.com/quasar098/limbos32/assets/154759975/9de567d4-0518-45f8-9a8b-2ba0abc70e1e)

**Comment by quasar098** [comment]
start the server

**Comment by MartinLlamas1** [comment]
That's the problem, crashes or closes less in 1s

**Comment by HHonzik** [comment]
open cmd in the install directory and run `server.py` and copy the output here

**Comment by MartinLlamas1** [comment]
Command..? (Sorry I'm not good at this) anyway putting server.py is an error
![image](https://github.com/quasar098/limbos32/assets/154759975/beab1397-b8fc-4251-af09-1971dcd2d802)

**Comment by EmK530** [comment]
you are not in the directory where server.py is

**Comment by MartinLlamas1** [comment]
and where the directory is?

**Comment by MinatoIsuki** [comment]
> and where the directory is?

`cd` to the folder where you are or enter `cmd` on the address bar for convenience.
![image](https://github.com/quasar098/limbos32/assets/102457568/f0e0bc2c-9736-463c-a1e2-c7c1291ca984)

**Comment by quasar098** [comment]
what @MinatoIsuki said

then, type in `python3 server.py` or perhaps `python server.py` like @HHonzik said

**Comment by MartinLlamas1** [comment]
I'm didn't undestand, I'm really new with the CMD and I'm very young, also that my english is very weak and most of the time I need the google translate, it would be easyer maybe passing me the commands you used.

**Comment by MinatoIsuki** [comment]
> I didn't undestand, I'm really new with the CMD and I'm very young, also that my english is very weak and most of the time I need the google translate, it would be easyer maybe passing me the commands you used.

Assuming you put the `limbos32-master` in the `Downloads` folder
```batch
cd "C:/Users/*Your username*/Downloads/limbos32-master"
python server.py
```
The `"` is included just in case your username have a space. If there isn't a space in your username, you can remove it.
If `python` doesn't work, try `python3`.

**Comment by MartinLlamas1** [comment]
I think it's my computer because says "The system can't find the specified path.", so I don't know that this gonna work so I'm closing this issue... if you want really to help me and if you got discord you can find me as "martin_llamas" good bye, and I'll try my best
