### ISSUE TITLE
weird directory error

### ISSUE THREAD

**Issue by emsoftworks** [quasar098/limbos32#26]
`C:\Users\fed\Desktop\limbos32-master>python spawn-all.py
The system cannot find the file C:\Users\fed\AppData\Local\Microsoft\WindowsApps\python3.exe.
The system cannot find the file C:\Users\fed\AppData\Local\Microsoft\WindowsApps\python3.exe.
The system cannot find the file C:\Users\fed\AppData\Local\Microsoft\WindowsApps\python3.exe.
The system cannot find the file C:\Users\fed\AppData\Local\Microsoft\WindowsApps\python3.exe.
The system cannot find the file C:\Users\fed\AppData\Local\Microsoft\WindowsApps\python3.exe.
The system cannot find the file C:\Users\fed\AppData\Local\Microsoft\WindowsApps\python3.exe.
The system cannot find the file C:\Users\fed\AppData\Local\Microsoft\WindowsApps\python3.exe.
The system cannot find the file C:\Users\fed\AppData\Local\Microsoft\WindowsApps\python3.exe.`

[vid](https://streamable.com/6yi2sr)

**Comment by emsoftworks** [comment]
![Screenshot_5](https://github.com/quasar098/limbos32/assets/154848349/754877d5-b4d5-4048-a6ee-ff54b7cd40b3)

**Comment by MinatoIsuki** [comment]
python3.exe is 0kb... wild.

Seems like you install Python through MS Store. Don't do that. Use the installer from [Python website](https://www.python.org/downloads/) instead. Make sure to select `Add python.exe to PATH` for convenience (else you will have to type the whole path to Python.

**Comment by quasar098** [comment]
what @MinatoIsuki said

**Comment by emsoftworks** [comment]
i did install it from the website tho..

**Comment by quasar098** [comment]
you have two pythons installed, which is annoying. uninstall the one from ms store

**Comment by HHonzik** [comment]
@quasar098 i have like 5 python installs 💀

**Comment by MinatoIsuki** [comment]
> @quasar098 i have like 5 python installs 💀

That's wild. How???

**Comment by quasar098** [comment]
@MinatoIsuki 

https://xkcd.com/1987/

**Comment by quasar098** [comment]
closing to inactivity
