### ISSUE TITLE
No module named Pygame and import pygame

### ISSUE THREAD

**Issue by pingui2003er** [quasar098/limbos32#28]
Hi my python said that I need to import pygame and ''No module named Pygame'' but I already installed pygame in my CMD but the system say the same error.
https://github.com/quasar098/limbos32/assets/155028340/ddeaa167-9a25-4ff2-9f71-cd595a553777

Here is a image of the error.

**Comment by quasar098** [comment]
list your modules real quick and send them back to me with `python3 -m pip list` iirc

**Comment by quasar098** [comment]
closing to inactivity
