### ISSUE TITLE
It refuses: error 10061

### ISSUE THREAD

**Issue by SilvoSNonsense** [quasar098/limbos32#29]
i'm not thqat familiar with code, but i did manage to get what you need to run this, but i still have a problem, my computer refuses to make it work, even tho i double clicked the server.py file, when i put the command in my cmd, it just refuses with error 10061

**Comment by SilvoSNonsense** [comment]
and yeah i accidadently closed it, please help

**Comment by quasar098** [comment]
run the server.py in cmd, and then run the spawn-all in a seperate cmd

**Comment by quasar098** [comment]
closing to inactivity
