### ISSUE TITLE
No directory

### ISSUE THREAD

**Issue by ThanhHuy2010** [quasar098/limbos32#32]
I was trying to install the dependencies by the instructions but it keeps showing this error:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by MinatoIsuki** [comment]
Assuming you are Vietnamese...
Nah let's just use English.

![image](https://github.com/quasar098/limbos32/assets/102457568/ae5ebab5-1859-4414-aba6-ba1b8dc6c7bc)
Check the directory you're in, there might be another `limbos32-master` inside.

**Comment by quasar098** [comment]
cd into the correct directory, what @MinatoIsuki said
