### ISSUE TITLE
No directory (I have installed python from the website)

### ISSUE THREAD

**Issue by GeometricAlexOfficial** [quasar098/limbos32#34]
![Captura de pantalla 2024-01-10 200219](https://github.com/quasar098/limbos32/assets/104314648/f72be4e4-f85b-4129-a34c-3f500c1e1007)
It gives me this error: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Even tho I have installed python 3.12 from the website and not from the MC Store

**Comment by MinatoIsuki** [comment]
There is another "limbos32-master" inside that folder. Do another `cd` and try to run it again.

**Comment by quasar098** [comment]
the above is true

**Comment by quasar098** [comment]
closing to inactivity
