### ISSUE TITLE
Errno 2

### ISSUE THREAD

**Issue by INOkentiy95** [quasar098/limbos32#38]
![image](https://github.com/quasar098/limbos32/assets/156944890/94c9c527-317a-4719-945e-9145282d1cc3)

**Comment by quasar098** [comment]
`dir` real quick

**Comment by INOkentiy95** [comment]
then?

**Comment by INOkentiy95** [comment]
![image](https://github.com/quasar098/limbos32/assets/156944890/88e9ff1a-3be0-43d0-b800-f69067b507d7)

**Comment by quasar098** [comment]
clone the repo again your requirements txt file is missing

**Comment by INOkentiy95** [comment]
repo???

**Comment by INOkentiy95** [comment]
![image](https://github.com/quasar098/limbos32/assets/156944890/4e2133fb-69c8-44cc-83f9-ad8096a9f396)

**Comment by Speronza** [comment]
i know what wrong, you have to cd the file twice. from downloads you will cd into the initial file, but after that you have to cd into the file inside of that aswell

**Comment by INOkentiy95** [comment]
![image](https://github.com/quasar098/limbos32/assets/156944890/5c457283-b0d9-4769-bf32-47513513f212)
what now

**Comment by quasar098** [comment]
uh hmm check the python version by using `python --version` or smth, use python3 command instead if it available

**Comment by MrocznyRycerz** [comment]
I have still problems, when I went to Downloads, then to limbos32-master, and after that I can't go to "Limbos", what should I do now?
![obraz_2024-01-26_224502259](https://github.com/quasar098/limbos32/assets/157849735/31d4ab6a-f184-4fed-bef9-69c883e8c650)

**Comment by quasar098** [comment]
redownload as said above

**Comment by quasar098** [comment]
closing to inactivity
