### ISSUE TITLE
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions while opening server.py

### ISSUE THREAD

**Issue by AkiTheFish** [quasar098/limbos32#41]
read title

python installation: python 3.10 x64
os: windows 11 home
administrator

steps to reproduce:
open server.py by double clicking or typing python "server.py" into cmd

![image](https://github.com/quasar098/limbos32/assets/99485078/69d68e24-06e2-48b7-9d99-c89e86136943)

**Comment by quasar098** [comment]
i have never seen that in my life

uh hm maybe try using an admin cmd, if not then a user cmd

also try restarting your computer to free up the ports

**Comment by AkiTheFish** [comment]
> i have never seen that in my life
> 
> uh hm maybe try using an admin cmd, if not then a user cmd
> 
> also try restarting your computer to free up the ports

i have tried both

**Comment by quasar098** [comment]
idk
