### ISSUE TITLE
[WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by limbogdfan** [quasar098/limbos32#42]
uhm how do i fix this
![Screenshot 2024-01-22 211158](https://github.com/quasar098/limbos32/assets/157422938/6b28c326-3965-44b7-bd49-93258818b325)

**Comment by quasar098** [comment]
i can tell from your username that you are a fan of LIMBO in gd

open a separate terminal and run server.py in the directory with the files in it

**Comment by limbogdfan** [comment]
it did a new thing but whats a __main__ module

**Comment by quasar098** [comment]
main module is the python file that is primarily running

**Comment by David280gg** [comment]
> i can tell from your username that you are a fan of LIMBO in gd
> 
> open a separate terminal and run server.py in the directory with the files in it
wdym separate terminal, what do i do, im new to this and i have this same problem

**Comment by David280gg** [comment]
i have this same problem and idk whats a separate terminal, im new to this

**Comment by limbogdfan** [comment]
![image](https://github.com/quasar098/limbos32/assets/157422938/2b1ac3e1-6bca-44aa-abd5-2d3f56d56ffc)

**Comment by limbogdfan** [comment]
cant find main module

**Comment by limbogdfan** [comment]
its because server.py does things behind the scenes so u run server.py then spawn all and put the 'main' python file in system32

**Comment by limbogdfan** [comment]
![image](https://github.com/quasar098/limbos32/assets/157422938/130067a7-4644-4039-9ce4-ac7c8d680647)

**Comment by limbogdfan** [comment]
![Screenshot 2024-01-27 094719](https://github.com/quasar098/limbos32/assets/157422938/d8224c88-b6da-4aae-88e7-9704cbff54c4)

**Comment by limbogdfan** [comment]
C:\Windows\System32

**Comment by limbogdfan** [comment]
then dont make any files in __System32__ and just place the __main__ python file called '__main__'

**Comment by limbogdfan** [comment]
then go to '__limbos32-master__' and run '__server.py__' then run '__spawn-all__'

**Comment by limbogdfan** [comment]
but i didnt make the whole tutorial so if u have a question i can answer it bc i figured how to do it

**Comment by quasar098** [comment]
closing to solved
