### ISSUE TITLE
i am having trouble opening python

### ISSUE THREAD

**Issue by Smilerr** [quasar098/limbos32#44]
I tried following the instructions given in the guide of the github page, but it didnt work. I tried "py," "python", and "python3". All didnt work. I tried adding to my "environment path" but when i checked, it was already there. Am i doing something wrong?
Respond when possible

**Comment by LoanSpac** [comment]
Yo, you can show your python version ? (python --version)

**Comment by Smilerr** [comment]
3.12

**Comment by quasar098** [comment]
when you add to env path add the directory not the file iirc

**Comment by KablammoMan** [comment]
> I tried following the instructions given in the guide of the github page, but it didnt work. I tried "py," "python", and "python3". All didnt work. I tried adding to my "environment path" but when i checked, it was already there. Am i doing something wrong? Respond when possible

I know this advice may seem basic, but I'm pretty sure the computer may need a restart to add the commands to PATH. Otherwise, maybe try complete uninstall (uninstall via control panel, then delete the Python directories to wipe all data), then reinstall.

**Comment by quasar098** [comment]
the above is true

**Comment by quasar098** [comment]
closing in activity
