### ISSUE TITLE
Errno 2 (no "Limbos")

### ISSUE THREAD

**Issue by MrocznyRycerz** [quasar098/limbos32#45]
Not sure what should I do now, can anyone help?
![image](https://github.com/quasar098/limbos32/assets/157849735/8530d3ec-dd63-4f41-a519-e45ba7c4376f)

**Comment by LoanSpac** [comment]
This error explain why you can't open 'requirements.txt' -> Are you sure to have the requirements file in your path ?

**Comment by quasar098** [comment]
ls real quick

**Comment by ChickenSandwich132** [comment]
you need to type downloads\limbos32-master\requirements.txt that's what worked for me

**Comment by quasar098** [comment]
i guess that works too

**Comment by quasar098** [comment]
ok
