### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by Nana6401** [quasar098/limbos32#46]
![Capture d'écran 2024-01-28 113145](https://github.com/quasar098/limbos32/assets/151875631/64a6804d-a843-4017-9652-12e95e697acb)

**Comment by Nana6401** [comment]
i tried everything but it just show this

**Comment by LoanSpac** [comment]
is because you have launch python and type this file, type CTRL + Z and retry

**Comment by quasar098** [comment]
closing to inactivity + solution is said already
