### ISSUE TITLE
unoptimized

### ISSUE THREAD

**Issue by WyitOwns** [quasar098/limbos32#5]
theres no delete button so im just gonna do this

**Comment by EMREOYUN** [comment]
Then do a pull request and contribute the code instead of complaining about it. It is a fun project, not a full game or something, what is the matter of this hate?

**Comment by Windowszin** [comment]
> this thing is slow as SHIT.
> 
> i get that you have to 5.4 seconds (why) for the game to start, but i modded the code like 2 decades ago to make it 0 and, as of writing this issue, the fucking thing is still ass-scooting its way to open a single key, HOW???!

STOP BEING RUDE

**Comment by WyitOwns** [comment]
sorry

**Comment by quasar098** [comment]
i am disappointed rn

even more disappointed that you claim to have "modded the code like 2 decades ago to make it 0" but then refuse to make a pull request.

this is not the purpose of open source.
