### ISSUE TITLE
[WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by kh01sm0k3** [quasar098/limbos32#52]
![Screenshot 2024-01-30 211616](https://github.com/quasar098/limbos32/assets/119870541/397d34da-6bcd-4923-bb6b-8521f4926faf)
[WinError 10061] No connection could be made because the target machine actively refused it
i don't know how to fix this bug, i try to find any solution on yt and stackoverflow but didn't not work, so who have any solution please help me.

**Comment by LoanSpac** [comment]
why you want to launch that in System32 ???
1. Is possible with a root shell
2. Do not use System32 file for open anything

**Comment by quasar098** [comment]
dont double click on the file and run as admin instead you should nav to the correct dir and run it using the cmd

**Comment by kh01sm0k3** [comment]
> why you want to launch that in System32 ???
> 
> 1. Is possible with a root shell
> 2. Do not use System32 file for open anything

i learned from yt so have this issue:v

**Comment by kh01sm0k3** [comment]
> why you want to launch that in System32 ???
> 
> 1. Is possible with a root shell
> 2. Do not use System32 file for open anything

and i run in on vs code and this happen again
![image](https://github.com/quasar098/limbos32/assets/119870541/f32a338c-edd7-4c55-b036-3d155fd6545a)

**Comment by quasar098** [comment]
run server.py in the background

**Comment by flattops123** [comment]
same issue
![image](https://github.com/quasar098/limbos32/assets/147597001/ff62aa91-b601-430d-bf03-ed7cfb18aef3)

**Comment by flattops123** [comment]
btw its windows 10

**Comment by LoanSpac** [comment]
Do you run server.py before ?
You must run server.py and spawn-all.py

**Comment by kh01sm0k3** [comment]
> same issue ![image](https://private-user-images.githubusercontent.com/147597001/303368936-ff62aa91-b601-430d-bf03-ed7cfb18aef3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1Mzc0NTIsIm5iZiI6MTcwNzUzNzE1MiwicGF0aCI6Ii8xNDc1OTcwMDEvMzAzMzY4OTM2LWZmNjJhYTkxLWI2MDEtNDMwZC1iZjAzLWVkN2NmYjE4YWVmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwMzUyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2QwNzY2YjNlM2EyNWFhOWFkODcwYWFjZTcwNjg0NWFmNjRmNzdhNTMzN2QzMzFiY2FiMTJlZmIyYTYzOGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v6rd_wCUMKrMMaxeQjfmdGEzc9h1IfVRbfMEvUuzq4s)

you should run server.py first, and then run spawn-all.py to run program smoothly

**Comment by quasar098** [comment]
closing to inactivity
