### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by VideoBotYT** [quasar098/limbos32#56]
everytime i run the script this happens

https://github.com/quasar098/limbos32/assets/113830775/59d68117-e6d8-424e-8791-6738591f0dd9

English version of last text: Cannot connect because the target computer has actively denied the connection

**Comment by LoanSpac** [comment]
Do you have run "server.py" ?
On my fork "server.py" is run automatically

**Comment by quasar098** [comment]
run the server in separate terminal
