### ISSUE TITLE
highlight which is the green key

### ISSUE THREAD

**Issue by lolcaken** [quasar098/limbos32#57]
I want to highlight which one is the correct key? Can someone help?

**Comment by LoanSpac** [comment]
You can just select the green key window, its working for me

**Comment by quasar098** [comment]
just get good at remembering which one is green

**Comment by HHonzik** [comment]
You could look at [my fork](https://github.com/HHonzik/limbos32) where there is a config.json file with a lot of configurables and to show the correct keys all of the time:
1. Rename sample_config.json to config.json
2. Find the line `"use_texture_pack": false,` and replace `false` with `true`
3. Start it with spawn-all.py
