### ISSUE TITLE
[WinError 10061] No connection could be made because the target machine actively refused i

### ISSUE THREAD

**Issue by DevilyTheCoder** [quasar098/limbos32#58]
![image](https://github.com/quasar098/limbos32/assets/153981208/b0d446f1-b13a-48bf-8e65-13a049c0a5b2)

I DID EVERYTHING RIGHT, WHAT DID I DO WRONG? HOW TO FIX IT?

**Comment by DevilyTheCoder** [comment]
server.py doesn't want to run. Here is a screenshot of what it says
![image](https://github.com/quasar098/limbos32/assets/153981208/1833fcdc-78e1-4ac0-b719-c3d011ea2fd6)

**Comment by quasar098** [comment]
run the server in the background

**Comment by DevilyTheCoder** [comment]
> run the server in the background

he cant open. He writes that there is no win32api, although I installed and even checked it. Also, there is no 306 version of pygame. What to do?

**Comment by quasar098** [comment]
but there does exist a 306 version ofpywin32 ?
