### ISSUE TITLE
[Feature Suggestion] Unfocus all window when the shuffling began

### ISSUE THREAD

**Issue by etherealxx** [quasar098/limbos32#59]
I noticed that the window will focus on the last generated key, and then user could just click the green key window before the shuffle began and it will track where the green key goes. My suggestion is to unfocus the focused window when the shuffling start, or make all of the window un-focus-able during the shuffling, if that's possible with pygame.

**Comment by quasar098** [comment]
idk maybe it is possible with win32 api or whatever

**Comment by etherealxx** [comment]
@quasar098 hi, excuse me. So, after I requested this feature and seeing no progress was made, i was thinking to "fix it myself", you know? So i forked your repo and thinking what i can do. However, i'm not that good at python, especially math, so i ended up confused. However, i have some knowledge on Godot Engine. So i started from your assets and code to make my on in that engine. It went pretty far, i could say. The code changes so much that almost nothing was coming from your repo (except the key png). So I'm near releasing this (probably tomorrow), and I'm kindly asking if i could change my fork's license to MIT? Since I'm not too comfortable with GPLv3, and again, it changed a lot that it's different from the source. (the repo in question: https://github.com/etherealxx/limbo-godot . I'll update the readme page later don't worry)
I'm aware of the case going on with your game got stolen by someone else on steam (i read it on reddit), that's unfortunate. So i think talking to you directly about this is the correct way.

**Comment by etherealxx** [comment]
Thanks for answering, really appreciated. Btw, about the feature on this issue page (unfocus thing), i'm not pushing you to add this feature. i know this is just a small project, an one off thing, and maybe you already moved on from this and have other more-serious project, so it's okay, totally understandable.

The reason that i forked from your project before is because i thought i could use most of your code, then modify it a bit. Turns out i mostly made it by myself. Then i was considering to use part of your code, like the array of key positions. But again, it's incompatible with my version which the keys are arranged with 4 rows and 2 columns, like the original limbo, unlike yours. So i use someone else's.

> although you might want to recreate the remote repo by deleting and creating the repo with the same name to prevent it being called a fork when it really isnt

you know, i could try contacting Github to remove the `forked from` label below my repo name, with proper reasoning of course. I've done it before and it works. Idk if those stuff are automated or not😅.

**Comment by quasar098** [comment]
i think win32api has a set window focus thing and that might be useful, or maybe there is a set window defocus thing idk

**Comment by quasar098** [comment]
it is done

**Comment by EMREOYUN** [comment]
For reference, fixed in commit dd9142a7f01a0edc02e82cfc108f734c32bb3de0
