### ISSUE TITLE
Issue: No module named 'win32api' ( I using window 10 )

### ISSUE THREAD

**Issue by xmanhne** [quasar098/limbos32#67]
help me fix

**Comment by crshqd** [comment]
this program only works on windows, thats why

**Comment by LoanSpac** [comment]
you must to install requirements.txt
(or "pip install win32api")

**Comment by xmanhne** [comment]
i installed requirements.txt but it did not work

**Comment by xmanhne** [comment]
pip install win32api error 
-Could not find a version that satisfies the requirement win32api (from versions: none)
-No matching distribution found for win32api

**Comment by LoanSpac** [comment]
go test :
```pip install win32api```

**Comment by quasar098** [comment]
no, it is pywin32 module
