### ISSUE TITLE
python: can't open file 'C:\\Users\\TuanSuaMay0904921929\\main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by vudinh1234** [quasar098/limbos32#70]
im a vietnamese idk how or what to do i need sum1 to teach

**Comment by vudinh1234** [comment]
idk how to even open up or set up the path or some

**Comment by quasar098** [comment]
navigate to the correct directory in your file structure in the terminal

**Comment by quasar098** [comment]
closing to inactivity
