### ISSUE TITLE
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by mishutik1** [quasar098/limbos32#71]
No matter how I try, I cannot open the requirements.txt file.

**Comment by quasar098** [comment]
check `dir` command and your current working directory

**Comment by FazeBWD** [comment]
it says `03/16/2024  09:46 PM    <DIR>          .
03/16/2024  09:46 PM    <DIR>          ..
03/16/2024  09:46 PM    <DIR>          limbos32-master
               0 File(s)              0 bytes
               3 Dir(s)  110,352,879,616 bytes free`

**Comment by FazeBWD** [comment]
i have the file extracted as well

**Comment by FazeBWD** [comment]
i dont need help now all you just do is if you have this: C:\Users\(your user)\Documents\limbos32-master\limbos32-master, then move requirements to C:\Users\(your user)\Documents\limbos32-master

**Comment by quasar098** [comment]
ok
