### ISSUE TITLE
Please help me from the beginning

### ISSUE THREAD

**Issue by yahyagirayesen123** [quasar098/limbos32#74]
Hello, I couldn't do this, can you help me with everything please?

**Comment by quasar098** [comment]
the issues tab is meant to be for bug reports

i am not tech support

please ask chat gpt or something

additionally, this is too vague

you "couldn't do this" ? what is that even supposed to mean

if you make another vague issue asking for helping in the wrong place i will ban you from this repository, do not do it again

**Comment by quasar098** [comment]
closing to incompetence

**Comment by yahyagirayesen123** [comment]
Niye böylesiniz

21 Mar 2024 Per 17:43 tarihinde quasar098 ***@***.***> şunu
yazdı:

**Comment by quasar098** [comment]
i am NOT tech support
