### ISSUE TITLE
Wrong module

### ISSUE THREAD

**Issue by idk3pzysk0** [quasar098/limbos32#77]
It says that in server.py in line 11 it says "from win32api  import GetSystemMetrics" and that there is no module named win32api. I've downloaded 32 Python and have 32 OS, I have no idea what is wrong.

**Comment by quasar098** [comment]
32 OS does not mean anything. if you mean a 32 bit OS, then I think it is time for you to upgrade your OS. most modern operating systems are 64 bit

win32api, despite having 32 in the name, does not rely on an 32 bit operating system being present

if you are on windows, win32api should be installed via pip (package name pywin32, not win32api)

if you are not on windows, something has gone terribly wrong.

**Comment by idk3pzysk0** [comment]
> 32 OS does not mean anything. if you mean a 32 bit OS, then I think it is time for you to upgrade your OS. most modern operating systems are 64 bit
> 
> win32api, despite having 32 in the name, does not rely on an 32 bit operating system being present
> 
> if you are on windows, win32api should be installed via pip (package name pywin32, not win32api)
> 
> if you are not on windows, something has gone terribly wrong.

Many thanks, man. I owe you for a life. How good to see this world still has geeks who are ready to answer mortal's questions.

**Comment by quasar098** [comment]
if you are unwilling to send screenshots of your exact issue then i cannot help you any further

**Comment by quasar098** [comment]
that is in the python interactive thing... just run cmd and input the command no python first

**Comment by EMREOYUN** [comment]
> > if you are unwilling to send screenshots of your exact issue then i cannot help you any further
> 
> ![Снимок экрана 2024-04-15 213442](https://github.com/quasar098/limbos32/assets/166364169/de2fbd49-18cb-4790-9e68-d90499caf0af)
> For sure, here. I was dumb not even remembering about attaching files function.

You can't run pip inside python. Instead of running python, run pip install <package name> from the console.

**Comment by quasar098** [comment]
closing to inactivity
