### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Deadmemerst** [quasar098/limbos32#9]
I did every single step right and everytime i try to open "spawn-all.py" it just hits me with this error
"python: can't open file 'C:\\Windows\\System32\\main.py': [errno 2] No such file or directory

**Comment by WyitOwns** [comment]
python is trying to open `main.py` on System32 which doesn't exist.

maybe go to the terminal at the directory the limbo game is in and type `python3 spawn-all.py`?

hope this helps

**Comment by EMREOYUN** [comment]
You need to `cd` to the directory that you downloaded the files or open the terminal from the folder.

**Comment by quasar098** [comment]
you do need to open cmd in the directory where the code is located and not just by typing in cmd into the windows search bar
